theme: jekyll-theme-minimal
logo: '/assets/logo.svg'
title: pyrewton
description: Bioinformatic pipeline for (i) the independent evaluation of CAZyme classifiers and (ii) creation of a comprehensive CAZome database.
