theme: jekyll-theme-architect
logo: '/assets/repophdcover.png'
title: pyrewton
description: Repository containing the Python package pyrewton for the independent evaluation of CAZyme classifiers and creation of a comprehensive CAZome database.
