theme: jekyll-theme-architect
logo: '/assets/repophdcover.png'
title: EastBIO PhD Project
description: Repository containing pyrewton program and documentation written to identify engineering candidates for advanced biocatalysis in biofuel production
